Controllers/ArticuloController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControlStock.Data;
using ControlStock.Models;
using Microsoft.AspNetCore.Identity;

namespace ControlStock.Controllers
{
    public class ArticuloController : Controller
    {
        private readonly MyDbContext _context;
        private readonly UserManager<MyUser> _userManager;
        private readonly ILogger<ArticuloController> _logger;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ArticuloController(MyDbContext context, UserManager<MyUser> userManager, ILogger<ArticuloController> logger, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _logger = logger;
        }

        // GET: Articulo
        public async Task<IActionResult> Index()
        {

            // Obtener el usuario logueado
            var user = await _userManager.GetUserAsync(User);
            var sections = await _context.UserPermissions
                .Where(a => a.UserId == user.Id)
                .Select(a => a.SectionId)
                .ToListAsync();
                
            var articulos = await _context.Articulos
            .Include(a => a.Marca)
            .ThenInclude(m => m.Rubro)
            .Where(a => sections.Contains(a.Marca.Rubro.SectionId))
            .ToListAsync();

            return View(articulos);
        }

        // GET: Articulo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articulo = await _context.Articulos
                .Include(a => a.Marca)
                .ThenInclude(m => m.Rubro)
                .FirstOrDefaultAsync(m => m.IdArticulo == id);
            if (articulo == null)
            {
                return NotFound();
            }

            return View(articulo);
        }

        // GET: Articulo/Create
        public async Task<IActionResult> Create(string returnUrl=null!)
        {
            // Capturar la URL de la página anterior
            string refererUrl = Request.Headers.Referer.ToString();

            // Validar que refererUrl no sea nulo o vacío y asignarlo a returnUrl si es una URL válida
            if (!string.IsNullOrEmpty(refererUrl) && Uri.IsWellFormedUriString(refererUrl, UriKind.Absolute))
            {
                returnUrl = new Uri(refererUrl).AbsolutePath;
            }

            // Asignar la URL predeterminada si returnUrl sigue siendo nulo
            returnUrl ??= Url.Content("~/");

            var user = await _userManager.GetUserAsync(User);

            var rubros = await _context.Rubros
                        .Where(rubro => _context.UserPermissions
                            .Where(up => up.UserId == user.Id)
                            .Select(up => up.SectionId)
                            .Contains(rubro.SectionId) &&
                                rubro.EliminadoLogico == false)
                        .ToListAsync();

            ViewData["UserId"] = user.Id;
            ViewData["Rubro"] = new SelectList(rubros, "IdRubro", "Name");
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        // POST: Articulo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdArticulo,Nombre,Descripcion,Activo,IdMarca,StockMin,UserId,Observaciones")] Articulo articulo, String? returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/Articulo/index");
            var user = articulo.UserId;
            if (ModelState.IsValid)
            {
                articulo.Nombre = articulo.Nombre.ToUpper();
                articulo.Descripcion = articulo.Descripcion?.ToUpper();
                articulo.Observaciones = articulo.Observaciones?.ToUpper();
                _context.Add(articulo);
                await _context.SaveChangesAsync();
                return Redirect(returnUrl);
            }
            var rubros = await _context.Rubros
                .Include(a => a.Section)
                .ThenInclude(a => a.UserPermissions)
                .Where(up => up.UserId == user && up.EliminadoLogico == false)
                .ToListAsync();

            ViewData["UserId"] = user;
            ViewData["Rubro"] = new SelectList(rubros, "IdRubro", "Name");
            return View(articulo);
        }

        // GET: Articulo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await _userManager.GetUserAsync(User);                   

            if (id == null)
            {
                return NotFound();
            }

            var articulo = await _context.Articulos
                    .Include(a => a.Marca)   // Incluir Marca
                    .ThenInclude(m => m.Rubro) // Incluir Rubro a través de Marca
                    .FirstOrDefaultAsync(m => m.IdArticulo == id);

            if (articulo == null)
            {
                return NotFound();
            }
            var rubros = await _context.Rubros
                        .Where(rubro => _context.UserPermissions
                            .Where(up => up.UserId == user.Id)
                            .Select(up => up.SectionId)
                            .Contains(rubro.SectionId) &&
                                rubro.EliminadoLogico == false)
                        .ToListAsync();

            var marcas = await _context.Marcas
                .Where(up => up.IdRubro == articulo.Marca.IdRubro)
                .ToListAsync();

            ViewData["UserId"] = user.Id;
            ViewData["IdRubro"] = new SelectList(rubros, "IdRubro", "Name",articulo.Marca.IdRubro);
            ViewData["IdMarca"] = new SelectList(marcas, "IdMarca", "MarcaName", articulo.IdMarca);
            return View(articulo);
        }

        // POST: Articulo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdArticulo,Nombre,Descripcion,Activo,IdMarca,StockMin,UserId,Observaciones")] Articulo articulo)
        {
            if (id != articulo.IdArticulo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    articulo.Nombre = articulo.Nombre.ToUpper();
                    articulo.Descripcion = articulo.Descripcion?.ToUpper();
                    articulo.Observaciones = articulo.Observaciones?.ToUpper();
                    _context.Update(articulo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticuloExists(articulo.IdArticulo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "MarcaName", articulo.IdMarca);
            ViewData["IdRubro"] = new SelectList(_context.Rubros, "IdRubro", "Name", articulo.Marca?.Rubro?.IdRubro);
            return View(articulo);
        }

        // GET: Articulo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articulo = await _context.Articulos
                .Include(a => a.Marca)
                .ThenInclude(m => m.Rubro)
                .FirstOrDefaultAsync(m => m.IdArticulo == id);
            if (articulo == null)
            {
                return NotFound();
            }

            return View(articulo);
        }

        // POST: Articulo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var articulo = await _context.Articulos.FindAsync(id);
            if (articulo != null)
            {
                _context.Articulos.Remove(articulo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticuloExists(int id)
        {
            return _context.Articulos.Any(e => e.IdArticulo == id);
        }

        // GET: Articulo/GetMarcasPorRubro
        public async Task<IActionResult> GetMarcasPorRubro(int idRubro)
        {

            var marcas = await _context.Marcas
                .Where(m => m.IdRubro == idRubro && m.EliminadoLogico == false) 
                .OrderBy(a => a.MarcaName)
                .ToListAsync();

            var articulos = await _context.Articulos
                .Where(a => a.EliminadoLogico == false && a.Marca.IdRubro == idRubro)
                .OrderBy(m => m.Nombre)
                .ToListAsync();
            var result = new
            {
                Marcas = marcas,
                Articulos = articulos
            };
            return Json(result);
        }

        // GET: Articulo/GetArticulosPorMarca
        public async Task<IActionResult> GetArticulosPorMarca(int idMarca)
        {

            var articulo = await _context.Articulos
                .Where(m => m.IdMarca == idMarca && m.EliminadoLogico == false)

Controllers/MarcaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControlStock.Data;
using ControlStock.Models;
using Microsoft.AspNetCore.Identity;
using System.Linq.Dynamic.Core;

namespace ControlStock.Controllers
{
    public class MarcaController : Controller
    {
        private readonly MyDbContext _context;
        private readonly UserManager<MyUser> _userManager;
        private readonly ILogger<MarcaController> _logger;
        private readonly RoleManager<IdentityRole> _roleManager;

        public MarcaController(MyDbContext context, UserManager<MyUser> user, ILogger<MarcaController> logger, RoleManager<IdentityRole> roleManager )
        {
            _context = context;
            _userManager = user;
            _roleManager = roleManager;
            _logger = logger;
        }

        // GET: Marca
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var marcas = await _context.Marcas
                         .Include(m => m.Rubro)
                         .Where(m => _context.UserPermissions
                             .Where(up => up.UserId == user.Id)
                             .Select(up => up.SectionId)
                             .Contains(m.Rubro.SectionId) && m.EliminadoLogico == false)
                             .ToListAsync();

            return View(marcas);
        }

        // GET: Marca/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas
                .Include(m => m.Rubro)
                .FirstOrDefaultAsync(m => m.IdMarca == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // GET: Marca/Create
        public async Task<IActionResult> Create(string returnUrl = null!)
        {
            // Capturar la URL de la página anterior
            string refererUrl = Request.Headers.Referer.ToString();

            // Validar que refererUrl no sea nulo o vacío y asignarlo a returnUrl si es una URL válida
            if (!string.IsNullOrEmpty(refererUrl) && Uri.IsWellFormedUriString(refererUrl, UriKind.Absolute))
            {
                returnUrl = new Uri(refererUrl).AbsolutePath;
            }

            // Asignar la URL predeterminada si returnUrl sigue siendo nulo
            returnUrl ??= Url.Content("~/");

            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var rubros = await _context.Rubros
                        .Where(rubro => _context.UserPermissions
                            .Where(up => up.UserId == user.Id)
                            .Select(up => up.SectionId)
                            .Contains(rubro.SectionId) &&
                                rubro.EliminadoLogico == false)
                        .ToListAsync();

                ViewData["UserId"] = user.Id;
            ViewData["IdRubro"] = new SelectList(rubros, "IdRubro", "Name");
            }
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        // POST: Marca/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdMarca,MarcaName,IdRubro,UserId")] Marca marca, string returnUrl = null!)
        {
            returnUrl = returnUrl ?? Url.Content("~/marca/index");
            try
            {
                if (ModelState.IsValid)
                {                    
                    marca.MarcaName = marca.MarcaName.ToUpper();
                    _context.Add(marca);
                    await _context.SaveChangesAsync();
                    return Redirect(returnUrl);
                }
                //ViewData["IdRubro"] = new SelectList(_context.Rubros, "IdRubro", "Name", marca.IdRubro);
                return View(marca);
            } 
            catch (Exception ex)
            {
                _logger.LogError(ex.Message, ex);
                return View();
            }           
        }

        // GET: Marca/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas.FindAsync(id);
            if (marca == null)
            {
                return NotFound();
            }

            var rubros = await _context.Rubros
                .Include(a => a.Section)
                .ThenInclude(a => a.UserPermissions
                    .Where(up => up.UserId == user.Id))
                .Where(up => up.EliminadoLogico == false)
                .ToListAsync();

            ViewData["UserId"] = user.Id;
            ViewData["IdRubro"] = new SelectList(rubros, "IdRubro", "Name", marca.IdRubro);
            return View(marca);
        }

        // POST: Marca/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdMarca,MarcaName,IdRubro,UserId")] Marca marca)
        {
            if (id != marca.IdMarca)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    marca.MarcaName = marca.MarcaName.ToUpper();
                    _context.Update(marca);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarcaExists(marca.IdMarca))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdRubro"] = new SelectList(_context.Rubros, "IdRubro", "Name", marca.IdRubro);
            return View(marca);
        }

        // GET: Marca/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas   
                .Include(m => m.Rubro)
                .FirstOrDefaultAsync(m => m.IdMarca == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // POST: Marca/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var marca = await _context.Marcas.FindAsync(id);
            if (marca != null)
            {
                marca.UserId = user.Id;
                marca.EliminadoLogico = true;
                //_context.Marcas.Remove(marca);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MarcaExists(int id)
        {
            return _context.Marcas.Any(e => e.IdMarca == id);
        }
    }
}

Views/Articulo/Create.cshtml
@model ControlStock.Models.Articulo

@{
    ViewData["Title"] = "Crear Articulo";
}

<h1>Crear Articulo Nuevo</h1>

<h4>Artículo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" name="returnUrl" value="@ViewBag.ReturnUrl" />
            <input asp-for="UserId" type="hidden" value="@ViewBag.UserId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" autocomplete="off" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripción</label>
                <input asp-for="Descripcion" class="form-control" autocomplete="off" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <label asp-for="Marca.IdRubro" class="control-label ">Rubro
                    <span data-bs-toggle="tooltip" data-bs-title="Agregar Rubro">
                        <a asp-controller="Rubroes" asp-action="Create" class="align-self-center fa fa-plus-circle" style="text-decoration: none;"></a>
                    </span>
                </label>
                <select id="rubroSelect" asp-for="Marca.IdRubro" class="form-control chosen-select" asp-items="ViewBag.Rubro">
                    <option>Seleccione un Rubro</option>
                </select>
                <span asp-validation-for="Marca.Rubro.IdRubro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdMarca" class="control-label">Marca
                    <span data-bs-toggle="tooltip" data-bs-title="Agregar Marca">
                        <a asp-controller="Marca" asp-action="Create" class="align-self-center fa fa-plus-circle" style="text-decoration: none;"></a>
                    </span>
                </label>
                <select id="marcaSelect" asp-for="IdMarca" class="form-control chosen-select" disabled>
                    <option>Seleccione una Marca</option>
                </select>
                <span asp-validation-for="IdMarca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockMin" class="control-label">Stock Minimo</label>
                <input asp-for="StockMin" class="form-control" autocomplete="off" />
                <span asp-validation-for="StockMin" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="Activo" class="control-label">Visible sin Stock </label>
                <input type="checkbox" asp-for="Activo" class="form-check-input"  />
                <span asp-validation-for="Activo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Observaciones" class="control-label">Observaciones</label>
                <textarea asp-for="Observaciones" rows="2" class="form-control"></textarea>
                <span asp-validation-for="Observaciones" class="text-danger"></span>
            </div>
            <div class="form-group">

            </div>
            <div class="form-group my-3">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al listado</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

   @*  <script>
        $(document).ready(function () {
            $('#rubroSelect').change(function () {
                var $marcaSelect = $('#marcaSelect');
                $marcaSelect.empty();
                var idRubro = $(this).val();
                if (idRubro) {
                    $.ajax({
                        url: '@Url.Action("GetMarcasPorRubro", "Articulo")',
                        type: 'GET',
                        dataType: 'json',
                        data: { idRubro: idRubro },
                        success: function (data) {
                            
                            $('#marcaSelect').prop('disabled', false);
                            $marcaSelect.append('<option value="">Seleccione una Marca</option>');
                            $.each(data.marcas, function (index, marca) {
                                $marcaSelect.append('<option value="' + marca.idMarca + '">' + marca.marcaName + '</option>');
                            });
                            $('#marcaSelect').trigger("chosen:updated");                            
                        },
                        error: function (xhr, status, error) {
                            console.log('Error: ' + error);
                        }
                    });
                } else {
                    $('#marcaSelect').empty().append('<option value="">Seleccione una Marca</option>');
                }
            });
        });
    </script>
 *@

}

Views/Articulo/Delete.cshtml
@model ControlStock.Models.Articulo

@{
    ViewData["Title"] = "Borrar";
}

<h1>Borrar Articulo</h1>

<h3>Está Seguro que desea borrar este Artículo?</h3>
<div>
    <h4>Articulo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
          Visible sin Stock
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca.MarcaName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca.IdRubro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca.Rubro.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdArticulo" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver al listado</a>
    </form>
</div>

Views/Articulo/Details.cshtml
@model ControlStock.Models.Articulo

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalle de Artículo</h1>

<div>
    <h4>Articulo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nombre:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            Descripción:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>       
        <dt class = "col-sm-2">
            Marca:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca.MarcaName)
        </dd>
        <dt class = "col-sm-2">
            Rubro:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca.Rubro.Name)
        </dd>
        <dt class="col-sm-2">
            Visible sin Stock
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
        <dt class="col-sm-2">
            Stock Minimo:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StockMin)
        </dd>
        <dt class="col-sm-2">
            Observaciones:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Observaciones)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdArticulo">Modificar</a> |
    <a asp-action="Index">Volver al Listado</a>
</div>

Views/Articulo/Edit.cshtml
@model ControlStock.Models.Articulo

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Articulo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger">Nombre</div>
            <input type="hidden" asp-for="IdArticulo" />
            <input asp-for="UserId" type="hidden" value="@ViewBag.UserId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label">Nombre</label>
                <input asp-for="Nombre" class="form-control" autocomplete="off" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripción</label>
                <input asp-for="Descripcion" class="form-control" autocomplete="off" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>  
            <div class="form-group">
                <label asp-for="Marca.Rubro" class="control-label "> Rubro
                    <span data-bs-toggle="tooltip" data-bs-title="Agregar Rubro">
                        <a asp-controller="Rubroes" asp-action="Create" class="align-self-center fa fa-plus-circle" style="text-decoration: none;"></a>
                    </span>
                </label>
                <select id="rubroSelect" asp-for="Marca.IdRubro" class="form-control chosen-select" asp-items="ViewBag.IdRubro"></select>
                <span asp-validation-for="Marca.IdRubro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdMarca" class="control-label"> Marca
                    <span data-bs-toggle="tooltip" data-bs-title="Agregar Marca">
                        <a asp-controller="Marca" asp-action="Create" class="align-self-center fa fa-plus-circle" style="text-decoration: none;"></a>
                    </span>
                </label>
                <select id="marcaSelect" asp-for="IdMarca" class="form-control chosen-select" asp-items="ViewBag.IdMarca"></select>
                <span asp-validation-for="IdMarca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockMin" class="control-label">Stock Minimo</label>
                <input type="number" asp-for="StockMin" class="form-control" autocomplete="off" />
                <span asp-validation-for="StockMin" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">Visible sin stock</label>
                <input class="form-check-input" asp-for="Activo" />
            </div>
            <div class="form-group">
                <label asp-for="Observaciones" class="control-label">Observaciones</label>
                <textarea asp-for="Observaciones" class="form-control" rows="2"></textarea>
                <span asp-validation-for="Observaciones" class="text-danger"></span>
            </div>

            <div class="form-group my-3">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al Listado</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    $(document).ready(function () {
        $('#rubroSelect').change(function () {
            var $marcaSelect = $('#marcaSelect');
            $marcaSelect.empty();
            var idRubro = $(this).val();
            if (idRubro) {
                $.ajax({
                    url: '@Url.Action("GetMarcasPorRubro", "Articulo")',
                    type: 'GET',
                    dataType: 'json',
                    data: { idRubro: idRubro },
                    success: function (data) {

                        $('#marcaSelect').prop('disabled', false);
                        $marcaSelect.append('<option value="">Seleccione una Marca</option>');
                        $.each(data, function (index, marca) {
                            $marcaSelect.append('<option value="' + marca.idMarca + '">' + marca.marcaName + '</option>');
                        });
                        $('#marcaSelect').trigger("chosen:updated");
                    },
                    error: function (xhr, status, error) {
                        console.log('Error: ' + error);
                    }
                });
            } else {
                $('#marcaSelect').empty().append('<option value="">Seleccione una Marca</option>');
            }
        });
    });
</script>