Models/Marca.cs
using ControlStock.Data;
using System.ComponentModel.DataAnnotations;

namespace ControlStock.Models;

public partial class Marca
{
    public int IdMarca { get; set; }

    public string MarcaName { get; set; } = null!;

    [Range(1, int.MaxValue, ErrorMessage = "El Rubro es obligatorio.")]
    public int IdRubro { get; set; }

    public bool EliminadoLogico { get; set; } = false;

    public string UserId { get; set; } = null!;
    public MyUser? User { get; set; } = null!;

    public virtual ICollection<Articulo> Articulos { get; set; } = new List<Articulo>();

    public virtual Rubro? Rubro { get; set; } = null!;
}

Areas/Identity/Pages/Account/Details.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ControlStock.Models;
using System.ComponentModel.DataAnnotations;
using ControlStock.Data;
using Microsoft.VisualBasic;

namespace SUAP_PortalOficios.Areas.Identity.Pages.Account
{
    public class DetailsModel : PageModel
    {

        private readonly UserManager<MyUser> _userManager;
        private readonly MyDbContext _context;
        private readonly ILogger<DetailsModel> _logger;
        private readonly RoleManager<IdentityRole> _roleManager;    

        public DetailsModel (
             UserManager<MyUser> userManager
            , MyDbContext context
            , ILogger<DetailsModel> logger,
             RoleManager<IdentityRole> roleManager
             )
        {

            _userManager = userManager;
            _context = context;
            _logger = logger;
            _roleManager = roleManager;

        }

        [BindProperty]
        public InputModel Input { get; set; }
       
        [BindProperty]
        public RolModel Rol { get; set; }

        [BindProperty(SupportsGet = true)]
        public string UserId { get; set; }

        public string ReturnUrl { get; set; }
        [BindProperty(SupportsGet = true)]
        public List<Section> Sections { get; set; }

        [BindProperty(SupportsGet = true)]
        public List<Scope> Scopes { get; set; }

        [BindProperty(SupportsGet = true)]
        public List<IdentityRole> Roles { get; set; }

        [BindProperty (SupportsGet = true)]
        public string UserRole { get; set; }

        public string UserName { get; set; }
        public bool IsLocked { get; set; }
        public List<roleList> Alcance { get; set; }

       
        public string StatusMessage { get; set; }

        public async Task<ActionResult> OnGetAsync(string id)
        {
            UserId = id;

            await inicializador(UserId);
         
            return Page();
        }

        public async Task<ActionResult> OnPostForm1(string id)
        {
            UserId = id;
            var user = await _userManager.FindByIdAsync(id);
                   
            if (user != null)
            { 
                ModelState.Clear();
                TryValidateModel(Input, nameof(Input));
                if (ModelState.IsValid)
                {
                    var userPermission = new UserPermission
                    {
                        UserId = user.Id,
                        SectionId = Input.SelectedSection,
                        ScopeId = Input.SelectedScope
                    };
                    _context.UserPermissions.Add(userPermission);
               
                    try
                    {
                        var result = await _context.SaveChangesAsync();
                        if (result > 0)
                        {
                            _logger.LogInformation("User modify the {0} account with succsess.", user.NormalizedUserName);
                            return RedirectToPage("/Account/Details", new { id = user.Id });
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, "Ha ocurrido un error, intente nuevamente");
                            return Page();
                        }
                    }
                    catch (Exception ex) {
                        if (ex.InnerException.HResult == -2146232060)
                        {
                            ModelState.AddModelError(string.Empty, "Este Usuario ya posee este alcance. Por favor elija otro");
                            await inicializador(UserId);
                            return Page();
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, ex.Message);
                            await inicializador(UserId);
                            return Page();
                        }                        
                    }
                }
            }
            await inicializador(UserId);
            return Page();
        }

        public async Task<ActionResult> OnPostForm3(string id)
            {
            try
            {
                var user = await _userManager.FindByIdAsync(id);
                var rolename = await _userManager.GetRolesAsync(user);

                var nombreRol = await _roleManager.FindByIdAsync(Rol.SelectedRolId);
                if (rolename.Count == 0)
                {

                    var res = await _userManager.AddToRoleAsync(user, nombreRol.Name);
                    if (res.Succeeded)
                    {
                        _logger.LogInformation("User modify the {0} account with succsess.", user.NormalizedUserName);
                        return RedirectToPage("/Account/Details", new { id = user.Id });
                    }
                }
                else
                {
                    var rol = await _roleManager.FindByNameAsync(rolename.FirstOrDefault());
                    if (rol.Id != Rol.SelectedRolId)
                    {
                        var resultRemove = await _userManager.RemoveFromRolesAsync(user, rolename);
                        if (resultRemove.Succeeded)
                        {
                            var resultAdd = await _userManager.AddToRoleAsync(user, nombreRol.Name);

                            if (resultAdd.Succeeded)
                            {
                                _logger.LogInformation("User modify the {0} account with succsess.", user.NormalizedUserName);
                                return RedirectToPage("/Account/Details", new { id = user.Id });
                            }
                        }
                    }
                    else
                    {
                        _logger.LogInformation("User modify the {0} account with succsess.", user.NormalizedUserName);
                        return RedirectToPage("/Account/Details", new { id = user.Id });
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Page();
            }

            var userRole = await _context.UserRoles
                               .Where(ur => ur.UserId == UserId)
                               .Select(ur => ur.RoleId)
                               .FirstOrDefaultAsync();
           if (userRole != null)
           {
                UserRole = userRole;
           }
           return Page();         
        }


        public async Task<ActionResult> OnPostDeleteRole(string userId, int scopeId, int sectionId)
        {
            try
            {
                var itemToDelete = await _context.UserPermissions.FirstOrDefaultAsync(u => u.UserId == userId && u.ScopeId == scopeId && u.SectionId == sectionId);
                if (itemToDelete != null)
                {
                    _context.UserPermissions.Remove(itemToDelete);
                    await _context.SaveChangesAsync();
                    return RedirectToPage("/Account/Details", new { id = userId });
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                await inicializador(userId);
                return Page();
            }
            return RedirectToPage("/Account/Details", new { id = userId });
        }
       

        public async Task<IActionResult> OnPostDeleteUserAsync(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return BadRequest("UserId is required.");
            }
            try
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user == null)
                {
                    return NotFound("User not found.");
                }

                //var res = await _userManager.DeleteAsync(user); // Eliminar el Usuario definitivamente (ojo!! Eliminado en casada de todas las tablas)

                if (user.LockoutEnd > DateTime.Now)
                {
                    user.LockoutEnd = null;
                }
                else { 
                    user.LockoutEnd = DateTimeOffset.MaxValue; // Bloquear indefinidamente (no genera problemas de eliminado en cascada)
                }
                var res = await _userManager.UpdateAsync(user);

                if (res.Succeeded)
                {
                    return RedirectToPage("/Account/Register");
                    
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                await inicializador(userId);
                return Page();
            }
            await inicializador(userId);
            return Page();
        }


        public async Task inicializador(string id )
        {
           
            var thisUser = await _userManager.GetUserAsync(User);
            var thisUserId = thisUser.Id;
           
            UserId = id;
         
            var sections = await _context.Sections
                .Where(section => _context.UserPermissions
                    .Any(up => up.SectionId == section.SectionId && up.UserId == thisUserId))
                .ToListAsync();         
          
            bool hasSpecificScope = await _context.UserPermissions
                                    .AnyAsync(up => up.UserId == thisUserId && up.ScopeId == 1);
            if (hasSpecificScope)
            {
                Scopes = await _context.Scopes.ToListAsync();

Controllers/RubroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControlStock.Data;
using ControlStock.Models;
using Microsoft.AspNetCore.Identity;

namespace ControlStock.Controllers
{
    public class RubroesController : Controller
    {
        private readonly MyDbContext _context;
        private readonly UserManager<MyUser> _userManager;
        private readonly ILogger<ArticuloController> _logger;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RubroesController(MyDbContext context, UserManager<MyUser> userManager, ILogger<ArticuloController> logger, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
            _roleManager = roleManager;
        }

        // GET: Rubroes
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var rubros = await _context.Rubros
                    .Where(rubro => _context.UserPermissions
                        .Where(up => up.UserId == user.Id)
                        .Select(up => up.SectionId)
                        .Contains(rubro.SectionId) &&
                            rubro.EliminadoLogico == false)
                    .ToListAsync();
                return View(rubros);
            }
            return View();
        }

        // GET: Rubroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rubro = await _context.Rubros
                .FirstOrDefaultAsync(m => m.IdRubro == id);
            if (rubro == null)
            {
                return NotFound();
            }

            return View(rubro);
        }


        // GET: Rubroes/Create
        public async Task<IActionResult> Create(string returnUrl = null!)
        {
            // Capturar la URL de la página anterior
            string refererUrl = Request.Headers.Referer.ToString();

            // Validar que refererUrl no sea nulo o vacío y asignarlo a returnUrl si es una URL válida
            if (!string.IsNullOrEmpty(refererUrl) && Uri.IsWellFormedUriString(refererUrl, UriKind.Absolute))
            {
                returnUrl = new Uri(refererUrl).AbsolutePath;
            }

            // Asignar la URL predeterminada si returnUrl sigue siendo nulo
            returnUrl ??= Url.Content("~/");

            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var sections = await _context.Sections
                    .Where(sections => _context.UserPermissions
                        .Where(up => up.UserId == user.Id)
                        .Select(up => up.SectionId)
                        .Contains(sections.SectionId))
                    .ToListAsync();
                ViewBag.Sections = new SelectList(sections, "SectionId", "Name");
                return View(); 
            }
            return View();
        }

        // POST: Rubroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRubro,Name,SectionId")] Rubro rubro, string? returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            var user = await _userManager.GetUserAsync(User);
            rubro.UserId = user.Id;
            ModelState.Remove("UserId");

            if (ModelState.IsValid)
            {
                rubro.Name = rubro.Name.ToUpper();
                _context.Add(rubro);
                await _context.SaveChangesAsync();
                return Redirect(returnUrl);
            }
            return View(rubro);
        }

        // GET: Rubroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rubro = await _context.Rubros.FindAsync(id);
            if (rubro == null)
            {
                return NotFound();
            }
            return View(rubro);
        }

        // POST: Rubroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRubro,Name, SectionId")] Rubro rubro)
        {
            ModelState.Remove("UserId");
            if (id != rubro.IdRubro)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);

            rubro.UserId = user.Id;

            if (ModelState.IsValid)
            {
                try
                {
                    rubro.Name = rubro.Name.ToUpper();
                    _context.Update(rubro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RubroExists(rubro.IdRubro))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rubro);
        }

        // GET: Rubroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rubro = await _context.Rubros
                .FirstOrDefaultAsync(m => m.IdRubro == id);
            if (rubro == null)
            {
                return NotFound();
            }

            return View(rubro);
        }

        // POST: Rubroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var user = await _userManager.GetUserAsync(User);
            var rubro = await _context.Rubros.FindAsync(id);
            if (rubro != null)
            {
                rubro.UserId = user.Id;
                rubro.EliminadoLogico = true;
                _context.Update(rubro);
                await _context.SaveChangesAsync();               
            }           
            return RedirectToAction(nameof(Index));
        }

        private bool RubroExists(int id)
        {
            return _context.Rubros.Any(e => e.IdRubro == id);
        }
    }
}

Views/Marca/Create.cshtml
@model ControlStock.Models.Marca

@{
    ViewData["Title"] = "Agregar";
}

<h1>Agregar Marcas</h1>

<h4>Marca</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" name="returnUrl" value="@ViewBag.ReturnUrl" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" value="@(ViewBag.UserId)" />            
            <div class="form-group">
                <label asp-for="IdRubro" class="control-label">Rubro
                    <span data-bs-toggle="tooltip" data-bs-title="Agregar Rubro">
                    <a asp-controller="Rubroes" asp-action="Create" class="align-self-center fa fa-plus-circle" style="text-decoration: none;"></a>
                </span>
                </label>
                <select asp-for="IdRubro" class="form-control" asp-items="ViewBag.IdRubro">
                    <option>Seleccione un rubro</option>
                </select>
                <span asp-validation-for="IdRubro" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="MarcaName" class="control-label">Nombre de la Marca</label>
                <input asp-for="MarcaName" class="form-control" autocomplete="off"/>
                <span asp-validation-for="MarcaName" class="text-danger"></span>
            </div>

            <div class="form-group mt-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al listado</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Marca/Delete.cshtml
@model ControlStock.Models.Marca

@{
    ViewData["Title"] = "Borrar";
}

<h1>Borrar Marca</h1>

<h3>Esta Seguro de que desea borrar esta Marca?</h3>
<div>
    <h4>Marca</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MarcaName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MarcaName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rubro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rubro.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdMarca" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver al Listado</a>
    </form>
</div>

Views/Marca/Details.cshtml
@model ControlStock.Models.Marca

@{
    ViewData["Title"] = "Detalle";
}

<h1>Detalle de Marca</h1>

<div>
    <h4>Marca</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MarcaName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MarcaName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rubro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rubro.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdMarca">Modificar</a> |
    <a asp-action="Index">Volver al Listado</a>
</div>

Views/Marca/Edit.cshtml
@model ControlStock.Models.Marca

@{
    ViewData["Title"] = "Modificar";
}

<h1>Modificar</h1>

<h4>Marca</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdMarca" />
            <input type="hidden" asp-for="UserId" value="@(ViewBag.UserId)" />
            <div class="form-group">
                <label asp-for="IdRubro" class="control-label">Rubro</label>
                <select asp-for="IdRubro" class="form-control" asp-items="ViewBag.IdRubro"></select>
                <span asp-validation-for="IdRubro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MarcaName" class="control-label"> Nombre</label>
                <input asp-for="MarcaName" class="form-control" autocomplete="off" />
                <span asp-validation-for="MarcaName" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary my-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al listado</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Marca/Index.cshtml
@model IEnumerable<ControlStock.Models.Marca>

@{
    ViewData["Title"] = "Index";
}

<div class="col-md-8">
<h1>Marcas</h1>

<p>
    <a asp-action="Create">Agregar Marca</a>
</p>
    <table class="table" id="tabla1" style="width:100%">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rubro)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MarcaName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rubro.Name)
            </td>
            <td class=" d-flex gap-1">
                <a asp-action="Edit" asp-route-id="@item.IdMarca" style="text-decoration: none; color:black" data-bs-toggle="tooltip" data-bs-title="Editar">
                    <i class="fa fa-pencil-square-o"></i>
                </a> |
                <a asp-action="Details" asp-route-id="@item.IdMarca" style="text-decoration: none; color:black" data-bs-toggle="tooltip" data-bs-title="Ver Detalle">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </a> |
                <a asp-action="Delete" asp-route-id="@item.IdMarca" style="text-decoration: none; color:black" data-bs-toggle="tooltip" data-bs-title="Eliminar">
                    <i class="fa fa-trash"></i>
                </a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
<script>
    var table = new DataTable('#tabla1', {
        language: {
            url: '../../lib/DataTables/Language.json',
        },
        scrollY: "40vh",
        deferRender: true,
        scroller: true
    });
</script>